layersFromGeoserver_json = [{
        projectName: "Cesc Niassa",
        parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_cesc_niassa/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_cesc_niassa%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_cesc_niassa/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_cesc_niassa%3Apovoados&maxFeatures=1000&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_cesc_niassa/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_cesc_niassa%3Aform_b_dados_lideres&maxFeatures=1000&outputFormat=application%2Fjson",
        l1_name: "cavateco_cesc_niassa:parcels",
        l2_name: "cavateco_cesc_niassa:povoados",
        l3_name: "cavateco_cesc_niassa:form_b_dados_lideres",
        box1: "cesc_box1",
        box2: "cesc_box2",
        box3: "cesc_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "cesc_uncheckbtn",
        thumbnailUrl: "./img/niassa4.png",
        description: "Formulário Líderes Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minima nobis soluta molestiae asperiores quae! Veritatis Formulário Líderes Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minima nobis soluta molestiae asperiores quae! Veritatis",
        code: "cesc_opacity",
        id_for_button_switch_color: "cesc_color",
    },
    {
        projectName: "NANA-Novo Madal",
        parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_novo_madal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_novo_madal%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_novo_madal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_novo_madal%3Apovoados&maxFeatures=1000&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_novo_madal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_novo_madal%3Aform_b_dados_lideres&maxFeatures=1000&outputFormat=application%2Fjson",
        l1_name: "cavateco_novo_madal:parcels",
        l2_name: "cavateco_novo_madal:povoados",
        l3_name: "cavateco_novo_madal:form_b_dados_lideres",
        box1: "madal_box1",
        box2: "madal_box2",
        box3: "madal_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "madal_uncheckbtn",
        thumbnailUrl: "./img/nana.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        code: "madal_opacity",
        id_for_button_switch_color: "madal_color",
    },
    {
        projectName: "Nitidae Zambezia",
        parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_nitidae/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_nitidae%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_nitidae/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_nitidae%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_nitidae/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_nitidae%3Aform_b_dados_lideres&maxFeatures=1000&outputFormat=application%2Fjson",
        l1_name: "cavateco_nitidae:parcels",
        l2_name: "cavateco_nitidae:povoados",
        l3_name: "cavateco_nitidae:form_b_dados_lideres",
        box1: "nitidae_box1",
        box2: "nitidae_box2",
        box3: "nitidae_box3",
        l1_defaultCheck: "checked",
        l2_defaultCheck: "false",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "nitidae_uncheckbtn",
        thumbnailUrl: "./img/nitidae.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        code: "nitidae_opacity",
        id_for_button_switch_color: "nitidae_color",
    },
    {
        projectName: "ANAM Ile",
        parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_ile/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_ile%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_ile/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_ile%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_ile/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_ile%3Aform_b_dados_lideres&outputFormat=application%2Fjson",
        l1_name: "cavateco_oram_ile:parcels",
        l2_name: "cavateco_oram_ile:povoados",
        l3_name: "cavateco_oram_ile:form_b_dados_lideres",
        box1: "ile_box1",
        box2: "ile_box2",
        box3: "ile_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "ile_uncheckbtn",
        thumbnailUrl: "./img/oram.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        code: "ile_opacity",
        id_for_button_switch_color: "ile_color",
    },
    {
        projectName: "ANAM Coastal",
        parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Apovoados&maxFeatures=1000&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aform_b_dados_lideres&maxFeatures=50&outputFormat=application%2Fjson",
        l1_name: "cavateco_oram_coastal:parcels",
        l2_name: "cavateco_oram_coastal:povoados",
        l3_name: "cavateco_oram_coastal:form_b_dados_lideres",
        box1: "coastal_box1",
        box2: "coastal_box2",
        box3: "coastal_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "coastal_uncheckbtn",
        thumbnailUrl: "./img/oram.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit",
        code: "coastal_opacity",
        id_for_button_switch_color: "coastal_color",
    },
    //new layers

    {
        projectName: "Gras HVP",
        //parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_hvp/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_hvp%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_hvp/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_hvp%3Aform_b_dados_lideres&maxFeatures=50&outputFormat=application%2Fjson",
        l1_name: "cavateco_gras_hvp:parcels",
        l2_name: "cavateco_gras_hvp:povoados",
        l3_name: "cavateco_gras_hvp:form_b_dados_lideres",
        box1: "hvp_box1",
        box2: "hvp_box2",
        box3: "hvp_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "hvp_uncheckbtn",
        thumbnailUrl: "./img/oram.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit",
        code: "hvp_opacity",
        id_for_button_switch_color: "hvp_color",
    },
    {
        projectName: "Gras Nampula",
        //parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_nampula/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_nampula%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_nampula/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_nampula%3Aform_b_dados_lideres&maxFeatures=50&outputFormat=application%2Fjson",
        l1_name: "cavateco_gras_nampula:parcels",
        l2_name: "cavateco_gras_nampula:povoados",
        l3_name: "cavateco_gras_nampula:form_b_dados_lideres",
        box1: "gras_nampula_box1",
        box2: "gras_nampula_box2",
        box3: "gras_nampula_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "gras_nampula_uncheckbtn",
        thumbnailUrl: "./img/terranossa.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit",
        code: "gras_nampula_opacity",
        id_for_button_switch_color: "gras_nampula_color",
    },
    {
        projectName: "Gras Zambézia",
        //parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_zambezia/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_zambezia%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_zambezia/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_zambezia%3Aform_b_dados_lideres&maxFeatures=50&outputFormat=application%2Fjson",
        l1_name: "cavateco_gras_zambezia:parcels",
        l2_name: "cavateco_gras_zambezia:povoados",
        l3_name: "cavateco_gras_zambezia:form_b_dados_lideres",
        box1: "gras_zambezia_box1",
        box2: "gras_zambezia_box2",
        box3: "gras_zambezia_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "gras_zambezia_uncheckbtn",
        thumbnailUrl: "./img/iTC-F.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit",
        code: "gras_zambezia_opacity",
        id_for_button_switch_color: "gras_zambezia_color",
    },
    {
        projectName: "Gras Niassa",
        //parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_niassa/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_niassa%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aform_b_dados_lideres&maxFeatures=50&outputFormat=application%2Fjson",
        l1_name: "cavateco_gras_niassa:parcels",
        l2_name: "cavateco_gras_niassa:povoados",
        l3_name: "cavateco_gras_niassa:form_b_dados_lideres",
        box1: "gras_niassa_box1",
        box2: "gras_niassa_box2",
        box3: "gras_niassa_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "gras_niassa_uncheckbtn",
        thumbnailUrl: "./img/niassa3.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit",
        code: "gras_niassa_opacity",
        id_for_button_switch_color: "gras_niassa_color",
    },
    {
        projectName: "WCS Niassa",
        //parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_oram_coastal/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_oram_coastal%3Aparcels&maxFeatures=1000&outputFormat=application%2Fjson",
        povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_wcs_niassa/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_wcs_niassa%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
        lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_wcs_niassa/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_wcs_niassa%3Aform_b_dados_lideres&maxFeatures=50&outputFormat=application%2Fjson",
        l1_name: "cavateco_wcs_niassa:parcels",
        l2_name: "cavateco_wcs_niassa:povoados",
        l3_name: "cavateco_wcs_niassa:form_b_dados_lideres",
        box1: "wcs_niassa_box1",
        box2: "wcs_niassa_box2",
        box3: "wcs_niassa_box3",
        l1_defaultCheck: "false",
        l2_defaultCheck: "checked",
        l3_defaultCheck: "false",
        id_for_button_uncheckAll: "wcs_niassa_uncheckbtn",
        thumbnailUrl: "./img/niassa2.png",
        description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit",
        code: "wcs_niassa_opacity",
        id_for_button_switch_color: "wcs_niassa_color",
    },
    // {
    //     projectName: "Aldeias",
    //     parcels_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_zambezia/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_zambezia%3Aaldeias_updated&maxFeatures=50&outputFormat=application%2Fjson",
    //     povoados_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_wcs_niassa/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_wcs_niassa%3Apovoados&maxFeatures=50&outputFormat=application%2Fjson",
    //     lideres_url: "http://cavateco.terrafirma.co.mz:8090/geoserver/cavateco_gras_zambezia/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cavateco_gras_zambezia%3Aaldeias_updated&maxFeatures=50&outputFormat=application%2Fjson",
    //     l1_name: "cavateco_wcs_niassa:parcels",
    //     l2_name: "cavateco_wcs_niassa:povoados",
    //     l3_name: "cavateco_gras_zambezia:aldeias_updated",
    //     box1: "aldeia_box1",
    //     box2: "aldeia_box2",
    //     box3: "aldeia_box3",
    //     l1_defaultCheck: "false",
    //     l2_defaultCheck: "false",
    //     l3_defaultCheck: "checked",
    //     id_for_button_uncheckAll: "aldeia_uncheckbtn",
    //     thumbnailUrl: "./img/aldeia.png",
    //     description: "Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit.Informação relativa a layer Lorem ipsum dolor sit amet consectetur, adipisicing elit",
    //     code: "aldeia_opacity",
    //     id_for_button_switch_color: "aldeia_color",
    // }
];